version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports: 
      - '5001:5001'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev